In [1]:
import numpy as np

array1 = np.array([3,0,9,12,6])
print(np.sort(array1))

[ 0  3  6  9 12]


In [2]:
import numpy as np

array1 = np.array([3,0,9,12,6])
array1=np.sort(array1)
print(array1)

[ 0  3  6  9 12]


In [4]:
array2 = np.array([[3,2,4],[5,0,1]])
print(np.sort(array2))

array3 = np.array(["cherry", "banana", "apple"])
print(np.sort(array3))

[[2 3 4]
 [0 1 5]]
['apple' 'banana' 'cherry']


In [10]:
arrayx =np.array([[2,1],[3,4]])
arrayy = np.array([[5,6]])
arrayz= np.array([[8,7],[9,10],[12,11]])
arraya=np.concatenate((arrayz,arrayx,arrayy),axis=0)
print(arraya)
arsrta=np.sort(arraya, axis=0)
print(arsrta)

[[ 8  7]
 [ 9 10]
 [12 11]
 [ 2  1]
 [ 3  4]
 [ 5  6]]
[[ 2  1]
 [ 3  4]
 [ 5  6]
 [ 8  7]
 [ 9 10]
 [12 11]]


In [20]:
newshape=arsrta.reshape(1,-1)
print(newshape)
array5 =np.array([[101,112,133,224],
                  [235,76,207,148],
                  [319,110,338,174]])
print(array5)

print("Sorted by axis 0",
      np.sort(array5,axis=0))
print("Sorted by axis 1",
      np.sort(array5,axis=1))

[[ 2  1  3  4  5  6  8  7  9 10 12 11]]
[[101 112 133 224]
 [235  76 207 148]
 [319 110 338 174]]
Sorted by axis 0 [[101  76 133 148]
 [235 110 207 174]
 [319 112 338 224]]
Sorted by axis 1 [[101 112 133 224]
 [ 76 148 207 235]
 [110 174 319 338]]


In [ ]:
# Unpacking arrays
tt = ([ [ [0, 1, 2, 3], [4, 5, 6, 7] ],
        [ [10, 11, 12, 13], [14, 15, 16, 17] ],
        [[20, 21, 22, 23], [24, 25, 26, 27] ] ])

a,b,c=tt

a0,a1,=a
b0,b1=b
c0,c1=c


In [ ]:
# unpacking series of nested elements PAY ATTENTION TO THE SQUARE BRACKETS
example = ([ [ [0, 1, 2, 3], [14, 15, 16, 17] ],
        [ [20, 21, 22, 23], [34, 35, 36, 37] ],
        [[40 ,41 ,42, 43], [54, 55, 56, 57] ] ])

[[[a,b,c,d], [e,f,g,h]],
 [[i,j,k,l], [m,n,o,p]],
 [[q,r,s,t], [u,v,w,x]]] = example
print(f"first group: {a}, {b}, {c}, {d}")
print(f"second group: {e}, {f}, {g}, {h}")
print(f"third group: {i}, {j}, {k}, {l}")


In [21]:
# slicing arrays
array2 = np.array([[1,2,3],[3,4,5], [4,5,6]])
print(array2[1:])

[[3 4 5]
 [4 5 6]]


In [28]:
a = np.array([[80,95,10],[50,90,60],[30,65,70]])
print(f'max is\n {np.max(a)}')
print(f'max at 0 is\n {np.max(a, axis=0)}')
print(f'max is\n {np.max(a,axis=1)}\n')
print(f'average\n is {np.average(a)}')
print(f'average at 0\n is {np.average(a,axis=0)}')
print(f'average\n is {np.average(a,axis=1)}\n')
print(f'sum is\n {np.sum(a)}')
print(f'sum is at 0\n {np.sum(a,axis=0)}')
print(f'sum is\n {np.sum(a,axis=1)}\n')
print(f'median is\n {np.median(a)}')
print(f'median is at 0\n {np.median(a,axis=0)}')
print(f'median is\n {np.median(a,axis=1)}')

max is
 95
max at 0 is
 [80 95 70]
max is
 [95 90 70]

average
 is 61.111111111111114
average at 0
 is [53.33333333 83.33333333 46.66666667]
average
 is [61.66666667 66.66666667 55.        ]

sum is
 550
sum is at 0
 [160 250 140]
sum is
 [185 200 165]

median is
 65.0
median is at 0
 [50. 90. 60.]
median is
 [80. 60. 65.]


In [3]:
import numpy as np
import pandas as pd

age = [20,40,60]
years=pd.Series(age)
print(years)
print(years[0])

0    20
1    40
2    60
dtype: int64
20


In [18]:
data = {
    "apples": [3, 2, 0, 1],
    "oranges": [0, 3, 7, 2]
}
print(data)
purchases=pd.DataFrame(data)
print('\n', purchases)
purchases=pd.DataFrame(data, index=["June", "Robert",'Lily','David'])
print("\n", purchases,'\n')

print('\n',purchases["oranges"],)

{'apples': [3, 2, 0, 1], 'oranges': [0, 3, 7, 2]}

    apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

         apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2 


 June      0
Robert    3
Lily      7
David     2
Name: oranges, dtype: int64


In [26]:
report={
    'Classes': ['Math','Science','Spanish','History','Health'],
    'Grades':[87,80,98,60,100]
}
results=pd.DataFrame(report)
print(results)
print(results.loc[3])
print(results.loc[[0,3]])
results=pd.DataFrame(report,index=['week1','Week2','week3','week4','Week5'])
print(results)
# print(results.loc['Week2','Week5'])

   Classes  Grades
0     Math      87
1  Science      80
2  Spanish      98
3  History      60
4   Health     100
Classes    History
Grades          60
Name: 3, dtype: object
   Classes  Grades
0     Math      87
3  History      60
       Classes  Grades
week1     Math      87
Week2  Science      80
week3  Spanish      98
week4  History      60
Week5   Health     100


In [34]:
population_list = [['Afghanistan', 1952, 8425333, 'Asia'],
            ['Australia', 1957, 9712569, 'Oceania'],
            ['Brazil', 1962, 76039390, 'Americas'],
            ['China', 1957, 637408000, 'Asia'],
            ['France', 1957, 44310863, 'Europe'],
            ['India', 1952, 3.72e+08, 'Asia'],
            ['South Africa', 1966, np.NaN, 'Africa'],
            ['United States', 1957, 171984000, 'Americas']]
df=pd.DataFrame(population_list, columns=['Country','Year','Population','Continent'])
print(df)
df.sort_values(by=["Continent"],inplace=True)
print('\n',df)
df.sort_values(by=['Population'], inplace=True, ascending=False)
print('\n',df)
df.sort_values(by=['Population'], inplace=True, na_position='first')
print('\n',df)

         Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6   South Africa  1966          NaN    Africa
7  United States  1957  171984000.0  Americas

          Country  Year   Population Continent
6   South Africa  1966          NaN    Africa
2         Brazil  1962   76039390.0  Americas
7  United States  1957  171984000.0  Americas
0    Afghanistan  1952    8425333.0      Asia
3          China  1957  637408000.0      Asia
5          India  1952  372000000.0      Asia
4         France  1957   44310863.0    Europe
1      Australia  1957    9712569.0   Oceania

          Country  Year   Population Continent
3          China  1957  637408000.0      Asia
5          India  1952  372000000.0      Asia
7  United States  1957  171984

In [37]:
population_list = [['Afghanistan', 1952, 8425333, 'Asia'],
            ['Australia', 1957, 9712569, 'Oceania'],
            ['Brazil', 1962, 76039390, 'Americas'],
            ['China', 1957, 637408000, 'Asia'],
            ['France', 1957, 44310863, 'Europe'],
            ['India', 1952, 3.72e+08, 'Asia'],
            ['South Africa', 1966, np.NaN, 'Africa'],
            ['United States', 1957, 171984000, 'Americas']]
df=pd.DataFrame(population_list, columns=['Country','Year','Population','Continent'])
df.sort_values(by=['Continent','Country'],inplace=True, ascending=[True,False])
print(df)

         Country  Year   Population Continent
6   South Africa  1966          NaN    Africa
7  United States  1957  171984000.0  Americas
2         Brazil  1962   76039390.0  Americas
5          India  1952  372000000.0      Asia
3          China  1957  637408000.0      Asia
0    Afghanistan  1952    8425333.0      Asia
4         France  1957   44310863.0    Europe
1      Australia  1957    9712569.0   Oceania


In [46]:
data={
    'Name':['Dakotah','Shelly','Trey','Chris','Sam','Nick','Habum','Carlos'],
    'Height':[6.0, 5.5, 5.8, 6.0, 5.10, 6.2, 6.0, 5.8],
    'Industry':['Finance','IT', "Personnel Tracking", "Hospital", "Govt Finance", "Software", "IT", "Water Resource Management"]
}
df=pd.DataFrame(data)
# print(df)
states=['Jersey','Missouri','Virginia','California','Ohio','Nevada','Nevada','California']
df['State']=states
# print('\n',df)
ages=[30,38,33,33,36,37,33,29]
df.insert(2,"Age",ages,allow_duplicates=True)
# print('\n',df)
pets = ["dog", "cat", "none", "dog", "fish", "none", "cat", "dog"]
df = df.assign(Pets=pets)
# print('\n',df)
sports = {"Shelly": "Volleyball", "Dakotah": "None", "Carlos": "Pickleball", "Trey": "Baseball", "Chris": "Volleyball", "Sam":"Soccer", "Habum":"Basketball", "Nick":"None"}
df["Sport"]=df["Name"].map(sports)
print('\n',df)


       Name  Height  Age                   Industry       State  Pets   
0  Dakotah     6.0   30                    Finance      Jersey   dog  \
1   Shelly     5.5   38                         IT    Missouri   cat   
2     Trey     5.8   33         Personnel Tracking    Virginia  none   
3    Chris     6.0   33                   Hospital  California   dog   
4      Sam     5.1   36               Govt Finance        Ohio  fish   
5     Nick     6.2   37                   Software      Nevada  none   
6    Habum     6.0   33                         IT      Nevada   cat   
7   Carlos     5.8   29  Water Resource Management  California   dog   

        Sport  
0        None  
1  Volleyball  
2    Baseball  
3  Volleyball  
4      Soccer  
5        None  
6  Basketball  
7  Pickleball  


In [9]:
# Day 3
import pandas as pd
file_name=('./sample_winterathletes.xlsx')
sheet_name="Athletes"
athletes=pd.read_excel(file_name,sheet_name=sheet_name)
athletes

Athletes Data 4 Athletes with 2 Sports        Athletes 2606   
0                    NaN                      NaN             NaN  NaN  \
1                   Name                    Sport     Nationality  Age   
2         ABBAS Muhammad            Alpine Skiing        Pakistan   23   
3          ABBOTT Jeremy           Figure Skating   United States   24   
4           ABLAEV Enver         Freestyle Skiing         Ukraine   30   
...                  ...                      ...             ...  ...   
2603         ZUEV Stepan            Alpine Skiing          Russia   21   
2604   ZURBRIGGEN Silvan            Alpine Skiing     Switzerland   28   
2605   ZUZULOVA Veronika            Alpine Skiing        Slovakia   25   
2606  ZVARICOVA Veronika                 Biathlon  Czech Republic   21   
2607  ZVEJNIEKS Kristaps            Alpine Skiing          Latvia   17   

     Unnamed: 4 Unnamed: 5  
0           NaN        NaN  
1         Wt kg         Ht  
2            55        168  
3           NaN        175  
4            68        169  
...         ...        ...  
2603         90        189  
2604         94        185  
2605         72        172  
2606         62        176  
2607         87        185  

[2608 rows x 6 columns]

In [12]:
import sqlite3
conn = sqlite3.connect("PitchForkDatabase.sqlite")
pfDB = pd.read_sql_query("select * from artists", conn)
pfDB

reviewid          artist
0         22703  massive attack
1         22721        krallice
2         22659    uranium club
3         22661         kleenex
4         22661         liliput
...         ...             ...
18826      1535         coldcut
18827      1341         cassius
18828      5376        mojave 3
18829      2413   don caballero
18830      3723  neil hamburger

[18831 rows x 2 columns]

In [15]:
green =pd.read_csv("GREENCOMPUTERS500.csv",index_col=0)
# green.info()
green

TOP500 Rank                   Name   
Rank                                       
1             170    NVIDIA DGX SuperPOD  \
2             330                   MN-3   
3               7  JUWELS Booster Module   
4             146               Spartan2   
5               5                 Selene   
...           ...                    ...   
496           204                  Betty   
497            37                    NaN   
498           419    Cumulus-Cascadelake   
499           124                  VSC-4   
500           479                  SWARM   

                                               Computer   
Rank                                                      
1     NVIDIA DGX A100, AMD EPYC 7742 64C 2.25GHz, NV...  \
2     MN-Core Server, Xeon Platinum 8260M 24C 2.4GHz...   
3     Bull Sequana XH2000 , AMD EPYC 7402 24C 2.8GHz...   
4     Bull Sequana XH2000 , AMD EPYC 7402 24C 2.8GHz...   
5     NVIDIA DGX A100, AMD EPYC 7742 64C 2.25GHz, NV...   
...                                                 ...   
496   Cray CS500, AMD EPYC 7542 32C 2.9GHz, InfiniBa...   
497   Cray XC40, Xeon E5-2695v4 18C 2.1GHz, Aries in...   
498   PowerEdge C6420, CRC-StackHPC,Xeon Platinum 82...   
499   ThinkSystem SD650, Xeon Platinum 8174 24C 3.1G...   
500   C4130/1028GQ, Xeon E5-2640v4 10C 2.4GHz, Intel...   

                                      Site        Manufacturer   
Rank                                                             
1                       NVIDIA Corporation              Nvidia  \
2                       Preferred Networks  Preferred Networks   
3          Forschungszentrum Juelich (FZJ)                Atos   
4                                     Atos                Atos   
5                       NVIDIA Corporation              Nvidia   
...                                    ...                 ...   
496      US Army Research Laboratory (ARL)                 HPE   
497   United Kingdom Meteorological Office            Cray/HPE   
498                University of Cambridge            Dell EMC   
499              Vienna Scientific Cluster              Lenovo   
500                       Wuhan University  SuperMicro/DellEMC   

             Country  Year   Segment Total Cores   
Rank                                               
1      United States  2020    Vendor      19,840  \
2              Japan  2020  Industry       1,664   
3            Germany  2020  Research     449,280   
4             France  2020    Vendor      23,040   
5      United States  2020    Vendor     555,520   
...              ...   ...       ...         ...   
496    United States  2020  Research      94,976   
497   United Kingdom  2016  Research     241,920   
498   United Kingdom  2020  Academic      37,632   
499          Austria  2019  Academic      37,920   
500            China  2019  Academic      32,640   

     Accelerator/Co-Processor Cores  ...    Accelerator/Co-Processor   
Rank                                 ...                               
1                            17,280  ...                 NVIDIA A100  \
2                               128  ...  Preferred Networks MN-Core   
3                           404,352  ...                 NVIDIA A100   
4                            20,736  ...                 NVIDIA A100   
5                           483,840  ...                 NVIDIA A100   
...                             ...  ...                         ...   
496                             NaN  ...                         NaN   
497                             NaN  ...                         NaN   
498                             NaN  ...                         NaN   
499                             NaN  ...                         NaN   
500                          30,720  ...      NVIDIA Tesla V100 SXM2   

     Cores per Socket               Processor Generation        System Model   
Rank                                                                           
1                  64           

In [18]:
#turning into csv file
cities = pd.DataFrame([["St. Louis", "Missouri"], ["Atlanta", "Georgia"]],
                        columns=["City", "State"])
# cities
cities.to_csv("cities.csv",index=False)# false removes index
df=pd.read_csv("cities.csv")
print(df)

        City     State
0  St. Louis  Missouri
1    Atlanta   Georgia


In [20]:
df=pd.read_csv("data.csv")
df
print(df.head(10))
print(df.tail(12))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0
     Duration  Pulse  Maxpulse  Calories
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


In [22]:
df=pd.read_csv("data.csv")
newdf=df.dropna()
# print(newdf.to_string())

In [26]:
df=pd.read_csv("data.csv")
df.fillna(130, inplace=True)
# df.fillna(130,inplace=True) #Replaces all null values
df["Calories"].fillna(130,inplace=True) #replaces certian column
# print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112     130.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [28]:
df=pd.read_csv("data.csv")
col_mean=round((df["Calories"].mean()),2)
print(col_mean)
df["Calories"].fillna(col_mean, inplace=True)#replaces null with either mean median or mode depending on what was called


375.79


In [34]:
df = pd.DataFrame({'X': [1, 2, 3, 4, 5],
                    'Y': [5, 6, 7, 8, 9],
                    'Z': ['z', 'y', 'x', 'w', 'v']})
df1=df.replace(to_replace=2,value=20)
# print(df1)
df2=df.replace(to_replace=[1,3,5],value=20)
# print(df2)
df3=df.replace(to_replace={1:10,'z':"zz","v":"vvv"})
# print(df3)
df4=df.replace(to_replace={"Y":{5:50},"X":{5:100}})
print(df4)

     X   Y  Z
0    1  50  z
1    2   6  y
2    3   7  x
3    4   8  w
4  100   9  v


In [48]:
import pandas as pd
df=pd.read_csv("data1.csv")
# print(df.to_string)
df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d")
print(df.to_string())

ValueError: time data "20220212" doesn't match format "%Y-%m-%d", at position 13. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [42]:
import pandas as pd
df=pd.read_csv("data1.csv")
df.loc[9,"Duration"]=45 #change data at location
print(df.to_string())
df.at[9,"Duration"]=30
print(df.at[9,"Duration"])

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2022-02-01    110       130     409.1
1         60  2022-02-02    117       145     479.0
2         60  2022-02-03    103       135     340.0
3         45  2022-02-04    109       175     282.4
4         45         NaN    117       148     406.0
5         60  2022-02-06    102       127     300.0
6         60  2022-02-07    110       136       NaN
7        450  2022-02-08    104       134     253.3
8         30  2022-02-09    109       133     195.1
9         45  2022-02-10     98       124     269.0
10        60  2022-02-11    103       147     329.3
11        60  2022-02-12    100       120     250.7
12       450  2022-02-08    104       134     253.3
13        60    20220212    100       120     250.7
14        45  2022-02-14    103       128     345.3
30


In [49]:
import pandas as pd
df=pd.read_csv("data.csv")
duration_series=df["Duration"]
# print(duration_series)
# for index, duration in enumerate(duration_series):
#     if duration>120:
#         df.loc[index,"Duration"] =120
# # print(df.to_string())
for x in df.index:
    if df.loc[x,"Duration"]>120:
        df.drop(x,inplace=True)
# print(df.to_string())

In [53]:
df=pd.read_csv("data1.csv")
# print(df.duplicated())
df.drop_duplicates(inplace=True)
# print(df.duplicated())
# print(df.to_string())

In [61]:
# titanic_data=pd.read_csv("titanic.csv")
# print(titanic_data.head())
# titanic_data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
# print(titanic_data.head())
col_names = ["Id", "Survived", 
                "Passenger Class", "Full Name", 
                "Gender", "Age", "SibSp", "Parch", 
                "Ticket Number", "Price", "Cabin", "Station"]

titanic_data=pd.read_csv("titanic.csv",names=col_names,skiprows=[0])
# print(titanic_data.head())

titanic_data.to_csv("use_titanic.csv",index=False)
df=pd.read_csv("use_titanic.csv")
print(df)

      Id  Survived  Passenger Class   
0      1         0                3  \
1      2         1                1   
2      3         1                3   
3      4         1                1   
4      5         0                3   
..   ...       ...              ...   
886  887         0                2   
887  888         1                1   
888  889         0                3   
889  890         1                1   
890  891         0                3   

                                             Full Name  Gender   Age  SibSp   
0                              Braund, Mr. Owen Harris    male  22.0      1  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...   