In [1]:
import numpy as np

array1 = np.array([3,0,9,12,6])
print(np.sort(array1))

[ 0  3  6  9 12]


In [2]:
import numpy as np

array1 = np.array([3,0,9,12,6])
array1=np.sort(array1)
print(array1)

[ 0  3  6  9 12]


In [4]:
array2 = np.array([[3,2,4],[5,0,1]])
print(np.sort(array2))

array3 = np.array(["cherry", "banana", "apple"])
print(np.sort(array3))

[[2 3 4]
 [0 1 5]]
['apple' 'banana' 'cherry']


In [10]:
arrayx =np.array([[2,1],[3,4]])
arrayy = np.array([[5,6]])
arrayz= np.array([[8,7],[9,10],[12,11]])
arraya=np.concatenate((arrayz,arrayx,arrayy),axis=0)
print(arraya)
arsrta=np.sort(arraya, axis=0)
print(arsrta)

[[ 8  7]
 [ 9 10]
 [12 11]
 [ 2  1]
 [ 3  4]
 [ 5  6]]
[[ 2  1]
 [ 3  4]
 [ 5  6]
 [ 8  7]
 [ 9 10]
 [12 11]]


In [20]:
newshape=arsrta.reshape(1,-1)
print(newshape)
array5 =np.array([[101,112,133,224],
                  [235,76,207,148],
                  [319,110,338,174]])
print(array5)

print("Sorted by axis 0",
      np.sort(array5,axis=0))
print("Sorted by axis 1",
      np.sort(array5,axis=1))

[[ 2  1  3  4  5  6  8  7  9 10 12 11]]
[[101 112 133 224]
 [235  76 207 148]
 [319 110 338 174]]
Sorted by axis 0 [[101  76 133 148]
 [235 110 207 174]
 [319 112 338 224]]
Sorted by axis 1 [[101 112 133 224]
 [ 76 148 207 235]
 [110 174 319 338]]


In [ ]:
# Unpacking arrays
tt = ([ [ [0, 1, 2, 3], [4, 5, 6, 7] ],
        [ [10, 11, 12, 13], [14, 15, 16, 17] ],
        [[20, 21, 22, 23], [24, 25, 26, 27] ] ])

a,b,c=tt

a0,a1,=a
b0,b1=b
c0,c1=c


In [ ]:
# unpacking series of nested elements PAY ATTENTION TO THE SQUARE BRACKETS
example = ([ [ [0, 1, 2, 3], [14, 15, 16, 17] ],
        [ [20, 21, 22, 23], [34, 35, 36, 37] ],
        [[40 ,41 ,42, 43], [54, 55, 56, 57] ] ])

[[[a,b,c,d], [e,f,g,h]],
 [[i,j,k,l], [m,n,o,p]],
 [[q,r,s,t], [u,v,w,x]]] = example
print(f"first group: {a}, {b}, {c}, {d}")
print(f"second group: {e}, {f}, {g}, {h}")
print(f"third group: {i}, {j}, {k}, {l}")


In [21]:
# slicing arrays
array2 = np.array([[1,2,3],[3,4,5], [4,5,6]])
print(array2[1:])

[[3 4 5]
 [4 5 6]]


In [28]:
a = np.array([[80,95,10],[50,90,60],[30,65,70]])
print(f'max is\n {np.max(a)}')
print(f'max at 0 is\n {np.max(a, axis=0)}')
print(f'max is\n {np.max(a,axis=1)}\n')
print(f'average\n is {np.average(a)}')
print(f'average at 0\n is {np.average(a,axis=0)}')
print(f'average\n is {np.average(a,axis=1)}\n')
print(f'sum is\n {np.sum(a)}')
print(f'sum is at 0\n {np.sum(a,axis=0)}')
print(f'sum is\n {np.sum(a,axis=1)}\n')
print(f'median is\n {np.median(a)}')
print(f'median is at 0\n {np.median(a,axis=0)}')
print(f'median is\n {np.median(a,axis=1)}')

max is
 95
max at 0 is
 [80 95 70]
max is
 [95 90 70]

average
 is 61.111111111111114
average at 0
 is [53.33333333 83.33333333 46.66666667]
average
 is [61.66666667 66.66666667 55.        ]

sum is
 550
sum is at 0
 [160 250 140]
sum is
 [185 200 165]

median is
 65.0
median is at 0
 [50. 90. 60.]
median is
 [80. 60. 65.]
