In [1]:
import numpy as np

array1 = np.array([3,0,9,12,6])
print(np.sort(array1))

[ 0  3  6  9 12]


In [2]:
import numpy as np

array1 = np.array([3,0,9,12,6])
array1=np.sort(array1)
print(array1)

[ 0  3  6  9 12]


In [4]:
array2 = np.array([[3,2,4],[5,0,1]])
print(np.sort(array2))

array3 = np.array(["cherry", "banana", "apple"])
print(np.sort(array3))

[[2 3 4]
 [0 1 5]]
['apple' 'banana' 'cherry']


In [10]:
arrayx =np.array([[2,1],[3,4]])
arrayy = np.array([[5,6]])
arrayz= np.array([[8,7],[9,10],[12,11]])
arraya=np.concatenate((arrayz,arrayx,arrayy),axis=0)
print(arraya)
arsrta=np.sort(arraya, axis=0)
print(arsrta)

[[ 8  7]
 [ 9 10]
 [12 11]
 [ 2  1]
 [ 3  4]
 [ 5  6]]
[[ 2  1]
 [ 3  4]
 [ 5  6]
 [ 8  7]
 [ 9 10]
 [12 11]]


In [20]:
newshape=arsrta.reshape(1,-1)
print(newshape)
array5 =np.array([[101,112,133,224],
                  [235,76,207,148],
                  [319,110,338,174]])
print(array5)

print("Sorted by axis 0",
      np.sort(array5,axis=0))
print("Sorted by axis 1",
      np.sort(array5,axis=1))

[[ 2  1  3  4  5  6  8  7  9 10 12 11]]
[[101 112 133 224]
 [235  76 207 148]
 [319 110 338 174]]
Sorted by axis 0 [[101  76 133 148]
 [235 110 207 174]
 [319 112 338 224]]
Sorted by axis 1 [[101 112 133 224]
 [ 76 148 207 235]
 [110 174 319 338]]


In [ ]:
# Unpacking arrays
tt = ([ [ [0, 1, 2, 3], [4, 5, 6, 7] ],
        [ [10, 11, 12, 13], [14, 15, 16, 17] ],
        [[20, 21, 22, 23], [24, 25, 26, 27] ] ])

a,b,c=tt

a0,a1,=a
b0,b1=b
c0,c1=c


In [ ]:
# unpacking series of nested elements PAY ATTENTION TO THE SQUARE BRACKETS
example = ([ [ [0, 1, 2, 3], [14, 15, 16, 17] ],
        [ [20, 21, 22, 23], [34, 35, 36, 37] ],
        [[40 ,41 ,42, 43], [54, 55, 56, 57] ] ])

[[[a,b,c,d], [e,f,g,h]],
 [[i,j,k,l], [m,n,o,p]],
 [[q,r,s,t], [u,v,w,x]]] = example
print(f"first group: {a}, {b}, {c}, {d}")
print(f"second group: {e}, {f}, {g}, {h}")
print(f"third group: {i}, {j}, {k}, {l}")


In [21]:
# slicing arrays
array2 = np.array([[1,2,3],[3,4,5], [4,5,6]])
print(array2[1:])

[[3 4 5]
 [4 5 6]]


In [28]:
a = np.array([[80,95,10],[50,90,60],[30,65,70]])
print(f'max is\n {np.max(a)}')
print(f'max at 0 is\n {np.max(a, axis=0)}')
print(f'max is\n {np.max(a,axis=1)}\n')
print(f'average\n is {np.average(a)}')
print(f'average at 0\n is {np.average(a,axis=0)}')
print(f'average\n is {np.average(a,axis=1)}\n')
print(f'sum is\n {np.sum(a)}')
print(f'sum is at 0\n {np.sum(a,axis=0)}')
print(f'sum is\n {np.sum(a,axis=1)}\n')
print(f'median is\n {np.median(a)}')
print(f'median is at 0\n {np.median(a,axis=0)}')
print(f'median is\n {np.median(a,axis=1)}')

max is
 95
max at 0 is
 [80 95 70]
max is
 [95 90 70]

average
 is 61.111111111111114
average at 0
 is [53.33333333 83.33333333 46.66666667]
average
 is [61.66666667 66.66666667 55.        ]

sum is
 550
sum is at 0
 [160 250 140]
sum is
 [185 200 165]

median is
 65.0
median is at 0
 [50. 90. 60.]
median is
 [80. 60. 65.]


In [3]:
import numpy as np
import pandas as pd

age = [20,40,60]
years=pd.Series(age)
print(years)
print(years[0])

0    20
1    40
2    60
dtype: int64
20


In [18]:
data = {
    "apples": [3, 2, 0, 1],
    "oranges": [0, 3, 7, 2]
}
print(data)
purchases=pd.DataFrame(data)
print('\n', purchases)
purchases=pd.DataFrame(data, index=["June", "Robert",'Lily','David'])
print("\n", purchases,'\n')

print('\n',purchases["oranges"],)

{'apples': [3, 2, 0, 1], 'oranges': [0, 3, 7, 2]}

    apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

         apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2 


 June      0
Robert    3
Lily      7
David     2
Name: oranges, dtype: int64


In [26]:
report={
    'Classes': ['Math','Science','Spanish','History','Health'],
    'Grades':[87,80,98,60,100]
}
results=pd.DataFrame(report)
print(results)
print(results.loc[3])
print(results.loc[[0,3]])
results=pd.DataFrame(report,index=['week1','Week2','week3','week4','Week5'])
print(results)
# print(results.loc['Week2','Week5'])

   Classes  Grades
0     Math      87
1  Science      80
2  Spanish      98
3  History      60
4   Health     100
Classes    History
Grades          60
Name: 3, dtype: object
   Classes  Grades
0     Math      87
3  History      60
       Classes  Grades
week1     Math      87
Week2  Science      80
week3  Spanish      98
week4  History      60
Week5   Health     100


In [34]:
population_list = [['Afghanistan', 1952, 8425333, 'Asia'],
            ['Australia', 1957, 9712569, 'Oceania'],
            ['Brazil', 1962, 76039390, 'Americas'],
            ['China', 1957, 637408000, 'Asia'],
            ['France', 1957, 44310863, 'Europe'],
            ['India', 1952, 3.72e+08, 'Asia'],
            ['South Africa', 1966, np.NaN, 'Africa'],
            ['United States', 1957, 171984000, 'Americas']]
df=pd.DataFrame(population_list, columns=['Country','Year','Population','Continent'])
print(df)
df.sort_values(by=["Continent"],inplace=True)
print('\n',df)
df.sort_values(by=['Population'], inplace=True, ascending=False)
print('\n',df)
df.sort_values(by=['Population'], inplace=True, na_position='first')
print('\n',df)

         Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6   South Africa  1966          NaN    Africa
7  United States  1957  171984000.0  Americas

          Country  Year   Population Continent
6   South Africa  1966          NaN    Africa
2         Brazil  1962   76039390.0  Americas
7  United States  1957  171984000.0  Americas
0    Afghanistan  1952    8425333.0      Asia
3          China  1957  637408000.0      Asia
5          India  1952  372000000.0      Asia
4         France  1957   44310863.0    Europe
1      Australia  1957    9712569.0   Oceania

          Country  Year   Population Continent
3          China  1957  637408000.0      Asia
5          India  1952  372000000.0      Asia
7  United States  1957  171984

In [37]:
population_list = [['Afghanistan', 1952, 8425333, 'Asia'],
            ['Australia', 1957, 9712569, 'Oceania'],
            ['Brazil', 1962, 76039390, 'Americas'],
            ['China', 1957, 637408000, 'Asia'],
            ['France', 1957, 44310863, 'Europe'],
            ['India', 1952, 3.72e+08, 'Asia'],
            ['South Africa', 1966, np.NaN, 'Africa'],
            ['United States', 1957, 171984000, 'Americas']]
df=pd.DataFrame(population_list, columns=['Country','Year','Population','Continent'])
df.sort_values(by=['Continent','Country'],inplace=True, ascending=[True,False])
print(df)

         Country  Year   Population Continent
6   South Africa  1966          NaN    Africa
7  United States  1957  171984000.0  Americas
2         Brazil  1962   76039390.0  Americas
5          India  1952  372000000.0      Asia
3          China  1957  637408000.0      Asia
0    Afghanistan  1952    8425333.0      Asia
4         France  1957   44310863.0    Europe
1      Australia  1957    9712569.0   Oceania


In [46]:
data={
    'Name':['Dakotah','Shelly','Trey','Chris','Sam','Nick','Habum','Carlos'],
    'Height':[6.0, 5.5, 5.8, 6.0, 5.10, 6.2, 6.0, 5.8],
    'Industry':['Finance','IT', "Personnel Tracking", "Hospital", "Govt Finance", "Software", "IT", "Water Resource Management"]
}
df=pd.DataFrame(data)
# print(df)
states=['Jersey','Missouri','Virginia','California','Ohio','Nevada','Nevada','California']
df['State']=states
# print('\n',df)
ages=[30,38,33,33,36,37,33,29]
df.insert(2,"Age",ages,allow_duplicates=True)
# print('\n',df)
pets = ["dog", "cat", "none", "dog", "fish", "none", "cat", "dog"]
df = df.assign(Pets=pets)
# print('\n',df)
sports = {"Shelly": "Volleyball", "Dakotah": "None", "Carlos": "Pickleball", "Trey": "Baseball", "Chris": "Volleyball", "Sam":"Soccer", "Habum":"Basketball", "Nick":"None"}
df["Sport"]=df["Name"].map(sports)
print('\n',df)


       Name  Height  Age                   Industry       State  Pets   
0  Dakotah     6.0   30                    Finance      Jersey   dog  \
1   Shelly     5.5   38                         IT    Missouri   cat   
2     Trey     5.8   33         Personnel Tracking    Virginia  none   
3    Chris     6.0   33                   Hospital  California   dog   
4      Sam     5.1   36               Govt Finance        Ohio  fish   
5     Nick     6.2   37                   Software      Nevada  none   
6    Habum     6.0   33                         IT      Nevada   cat   
7   Carlos     5.8   29  Water Resource Management  California   dog   

        Sport  
0        None  
1  Volleyball  
2    Baseball  
3  Volleyball  
4      Soccer  
5        None  
6  Basketball  
7  Pickleball  
